# Generated by Django 4.1.5 on 2023-02-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at']},
        ),
    ]
