# Generated by Django 4.1.5 on 2023-02-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='social_net.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='social_net.blog'),
            preserve_default=False,
        ),
    ]
