# Generated by Django 4.1.5 on 2023-09-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0002_alter_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
