# Generated by Django 4.1.5 on 2023-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0008_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
