# Generated by Django 4.1.5 on 2023-10-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0011_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="social_net.tag"),
        ),
    ]
