# Generated by Django 4.1.5 on 2023-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0012_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count_of_posts',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во постов блога'),
        ),
    ]
