# Generated by Django 4.1.5 on 2023-11-11 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_net', '0013_blog_count_of_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(related_name='blog_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
