# Generated by Django 4.1.5 on 2023-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0017_alter_post_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="count_of_commentaries",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кол-во комментариев блога"
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="comment_id",
            field=models.PositiveIntegerField(default=0, verbose_name="ID комментария"),
            preserve_default=False,
        ),
    ]
