# Generated by Django 4.1.5 on 2023-11-18 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_net', '0019_alter_commentary_comment_id_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(related_name='alex', to=settings.AUTH_USER_MODEL),
        ),
    ]
