# Generated by Django 4.1.5 on 2023-12-05 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_net", "0020_post_liked_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="commentary",
            options={},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="alex", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="social_net.tag"),
        ),
    ]
