# Generated by Django 4.1.5 on 2023-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0021_alter_blog_options_alter_commentary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
