# Generated by Django 4.1.5 on 2023-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0022_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
