# Generated by Django 4.1.5 on 2024-01-13 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_net", "0023_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="blog_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
