# Generated by Django 4.1.5 on 2024-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0029_invite_admin_invite_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Статус приглашения'),
        ),
    ]
