# Generated by Django 4.1.5 on 2024-11-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0031_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(default='icy.jpg', upload_to='blog_avatars/'),
        ),
    ]
