# Generated by Django 4.1.5 on 2024-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0032_blog_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='ax.jpg', upload_to='post_images/'),
        ),
    ]
