# Generated by Django 4.1.5 on 2024-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0037_blog_dzen_link_blog_email_blog_ok_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="avatar_small",
            field=models.ImageField(
                default="icy_small.png", upload_to="blog_avatars_small/"
            ),
        ),
    ]
