# Generated by Django 4.1.5 on 2024-12-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0038_blog_avatar_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social_net.commentary'),
        ),
    ]
