# Generated by Django 5.1.4 on 2024-12-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0040_blog_pinned_post_commentary_is_edited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="pinned_post",
        ),
    ]
