# Generated by Django 5.1.4 on 2025-01-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0044_post_pinned_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_allowed",
            field=models.BooleanField(
                default=True, verbose_name="Разрешены ли комментарии"
            ),
        ),
    ]
