# Generated by Django 5.1.4 on 2025-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0045_post_comments_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(default="banner.jpg", upload_to="blog/"),
        ),
    ]
