# Generated by Django 5.1.5 on 2025-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0051_alter_commentary_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='liked_by_author',
            field=models.BooleanField(default=False),
        ),
    ]
