# Generated by Django 5.1.5 on 2025-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0052_commentary_liked_by_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="map",
            field=models.TextField(default=0, verbose_name="Ссылка на карту"),
            preserve_default=False,
        ),
    ]
