# Generated by Django 5.1.5 on 2025-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0053_blog_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="map",
            field=models.TextField(blank=True, verbose_name="Ссылка на карту"),
        ),
    ]
