# Generated by Django 5.1.5 on 2025-02-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0058_alter_blog_avatar_alter_blog_avatar_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Тематика'),
        ),
    ]
