# Generated by Django 5.1.6 on 2025-03-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0060_alter_blog_avatar_alter_blog_avatar_small_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="ok_link",
        ),
    ]
