# Generated by Django 5.1.6 on 2025-04-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0064_alter_commentary_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social_net.commentary'),
        ),
    ]
