# Generated by Django 5.1.6 on 2025-04-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0066_notification_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="post",
        ),
    ]
