# Generated by Django 5.1.6 on 2025-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0072_commentary_pinned_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_is_hidden',
            field=models.BooleanField(default=False, verbose_name='Не показывать автора'),
        ),
    ]
