# Generated by Django 5.2 on 2025-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0076_alter_post_author_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="pinned_post",
        ),
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="Закреплён ли"),
        ),
    ]
