# Generated by Django 5.1.6 on 2025-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0078_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
