# Generated by Django 5.1.6 on 2025-05-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0079_postimage_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="description",
        ),
    ]
