# Generated by Django 5.1.5 on 2025-10-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0080_remove_postimage_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
