# Generated by Django 5.1.5 on 2025-10-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_net", "0081_delete_invite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
