# Generated by Django 5.1.5 on 2025-10-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_parent_comment_and_more"),
        ("social_net", "0082_delete_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Commentary",
        ),
    ]
