# Generated by Django 5.1.5 on 2025-10-18 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social_net", "0082_delete_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commentary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="Тело комментария")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "comment_id",
                    models.PositiveIntegerField(
                        null=True, verbose_name="ID комментария"
                    ),
                ),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Лайки")),
                (
                    "dislikes",
                    models.PositiveIntegerField(default=0, verbose_name="Дизлайки"),
                ),
                ("is_edited", models.BooleanField(default=False)),
                ("liked_by_author", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disliked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="disliked_commentaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_commentaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pinned_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_commentaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="social_net.post",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.commentary",
                    ),
                ),
            ],
        ),
    ]
