# Generated by Django 4.1.5 on 2023-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0019_alter_commentary_comment_id_alter_tag_name'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to='social_net.blog'),
        ),
    ]
