# Generated by Django 4.1.5 on 2024-11-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='icy.jpg', upload_to='images/'),
        ),
    ]
