# Generated by Django 5.1.4 on 2024-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_userprofile_avatar"),
        ("social_net", "0039_commentary_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarks", to="social_net.post"
            ),
        ),
    ]
