# Generated by Django 5.1.5 on 2025-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0008_userprofile_date_of_birth_userprofile_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(null=True, verbose_name="Возраст"),
        ),
    ]
