# Generated by Django 5.1.5 on 2025-10-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="parent_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comment",
                to="comments.commentary",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="replied_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replied_comment",
                to="comments.commentary",
            ),
        ),
    ]
